{
 "title": "Prometheus Exporters Overview",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(process_start_time_seconds{node_name=~\"$node_name\"}, service_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prometheus Exporters Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg CPU Usage per Node",
   "type": "stat",
   "description": "Shows the average CPU usage in percent per host for all exporters. An Exporter is a software library that provides metrics to PMM.\n\nNote that the CPU usage is only the CPU usage of the exporter itself. It does not include the additional resource usage that is required to produce metrics by the application or operating system.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum(rate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$node_name\"}[$interval]) or irate(process_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$node_name\"}[5m]) or\nlabel_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[$interval]),\"node_name\",\"pmm-server\",\"\",\"\") or\nlabel_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[5m]),\"node_name\",\"pmm-server\",\"\",\"\")) by (node_name)) / \ncount(node_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$node_name\"}) by (node_name) * 100 or\nsum by (node_name) ((max_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"total\"}[$interval]) or \nmax_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"total\"}[5m]))))"
    }
   ]
  },
  {
   "title": "Avg Memory Usage per Node",
   "type": "stat",
   "description": "Shows the Exporters average Memory usage per host. An Exporter is a software library that provides metrics to PMM.\n\nNote that the Memory usage is only the Memory usage of the exporter itself. It does not include the additional memory usage that is required to produce metrics by the application or operating system.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(\nmax_over_time(process_resident_memory_bytes{job=~\".*exporter.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[$interval]) or max_over_time(process_resident_memory_bytes{job=~\".*exporter.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[5m]) or\n(sum by (node_name) (label_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[$interval]),\"node_name\",\"pmm-server\",\"\",\"\") or\nlabel_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[5m]),\"node_name\",\"pmm-server\",\"\",\"\"))) * count by (node_name) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"node_name\", \"pmm-server\", \"\", \"\"))\n) by (node_name))"
    }
   ]
  },
  {
   "title": "Monitored Nodes",
   "type": "stat",
   "description": "Shows the number of monitored hosts that are running Exporters. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(count(process_open_fds{job=~\".*exporter.*\",node_name=~\"$node_name\"}) by (node_name))"
    }
   ]
  },
  {
   "title": "Exporters Running",
   "type": "stat",
   "description": "Shows the total number of Exporters running with this PMM Server instance. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(count by (agent_type) (process_cpu_seconds_total{node_name=~\"$node_name\"}) or count by (agent_type) (label_replace(label_replace(process_cpu_seconds_total{job=~\"rds.*\"},\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\"))  * count by (agent_type) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"agent_type\", \"rds_exporter\", \"\", \"\")))"
    }
   ]
  },
  {
   "title": "Prometheus Exporters Resource Usage by Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "Plots the Exporters' CPU usage across each monitored host (by default, All hosts). An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max((sum(rate(process_cpu_seconds_total{job=~\".*exporter.*|^vmagent.*\",node_name=~\"$node_name\"}[$interval]) or irate(process_cpu_seconds_total{job=~\".*exporter.*|^vmagent.*\",node_name=~\"$node_name\"}[5m]) or\nlabel_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[$interval]),\"node_name\",\"pmm-server\",\"\",\"\") or\nlabel_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[5m]),\"node_name\",\"pmm-server\",\"\",\"\")) by (node_name)) / \ncount(node_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$node_name\"}) by (node_name) *100 or\nsum by (node_name) ((max_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"total\"}[$interval]) or \nmax_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"total\"}[5m]))),100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Plots the Exporters' Memory usage across each monitored host (by default, All hosts). An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\nmax_over_time(process_resident_memory_bytes{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[$interval]) or max_over_time(process_resident_memory_bytes{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[5m]) or\n(sum by (node_name) (label_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[$interval]),\"node_name\",\"pmm-server\",\"\",\"\") or\nlabel_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[5m]),\"node_name\",\"pmm-server\",\"\",\"\"))) * count by (node_name) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"node_name\", \"pmm-server\", \"\", \"\"))\n) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Prometheus Resource usage by Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "CPU Cores Used",
   "type": "graph",
   "description": "Shows the Exporters' CPU Cores used for each type of Exporter. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (agent_type) (rate(process_cpu_seconds_total{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[$interval]) or irate(process_cpu_seconds_total{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[5m]) or avg by (agent_type) (label_replace(label_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[$interval]),\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\") or label_replace(label_replace(irate(process_cpu_seconds_total{job=~\"rds.*\"}[5m]),\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\")) * count by (agent_type) (label_replace(process_cpu_seconds_total{instance=~\"$node_name\",job=\"prometheus\"},\"agent_type\", \"rds_exporter\", \"\", \"\"))\n)",
     "legendFormat": "{{agent_type}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the Exporters' memory used for each type of Exporter. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (agent_type) (max_over_time(process_resident_memory_bytes{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[$interval]) or\nmax_over_time(process_resident_memory_bytes{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[5m]) or avg by (agent_type) (label_replace(label_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[$interval]),\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\") or label_replace(label_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[5m]),\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\")) * count by (agent_type) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"agent_type\", \"rds_exporter\", \"\", \"\"))\n)",
     "legendFormat": "{{agent_type}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "node_name" },
  { "title": "Node name", "type": "text", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 }, "options": { "content": "$node_name" } },
  {
   "title": "CPU Used",
   "type": "stat",
   "description": "Show the CPU usage as a percentage for all Exporters on a per-host basis. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=~\".*exporter.*|^vmagent.*\",node_name=~\"$node_name\"}[$interval]) or irate(process_cpu_seconds_total{job=~\".*exporter.*|^vmagent.*\",node_name=~\"$node_name\"}[5m]) or\nlabel_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[$interval]),\"node_name\",\"pmm-server\",\"\",\"\") or\nlabel_replace(rate(process_cpu_seconds_total{job=~\"rds.*\"}[5m]),\"node_name\",\"pmm-server\",\"\",\"\")) by (node_name)) / \ncount(node_cpu_seconds_total{job=~\".*exporter.*\",node_name=~\"$node_name\"}) by (node_name) * 100 or\nsum by (node_name) ((max_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"total\"}[$interval]) or \nmax_over_time(node_cpu_average{node_name=~\"$node_name\", mode=\"total\"}[5m])))"
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "stat",
   "description": "Shows total Memory Used by Exporters on a per-host basis. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\nmax_over_time(process_resident_memory_bytes{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[$interval]) or max_over_time(process_resident_memory_bytes{job=~\".*exporter.*|^vmagent.*\",job!~\"rds.*\",node_name=~\"$node_name\"}[5m]) or\n(sum by (node_name) (label_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[$interval]),\"node_name\",\"pmm-server\",\"\",\"\") or\nlabel_replace(max_over_time(process_resident_memory_bytes{job=~\"rds.*\"}[5m]),\"node_name\",\"pmm-server\",\"\",\"\"))) * count by (node_name) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"node_name\", \"pmm-server\", \"\", \"\"))\n) by (node_name)"
    }
   ]
  },
  {
   "title": "Exporters Running",
   "type": "stat",
   "description": "Shows the number of Exporters running on a per-host basis. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (agent_type) (process_cpu_seconds_total{node_name=~\"$node_name\"}) or count by (agent_type) (label_replace(label_replace(process_cpu_seconds_total{job=~\"rds.*\"},\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\"))  * count by (agent_type) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"agent_type\", \"rds_exporter\", \"\", \"\")))"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "sum by (agent_type) (count by (agent_type) (process_cpu_seconds_total{node_name=~\"$node_name\"}) or count by (agent_type) (label_replace(label_replace(process_cpu_seconds_total{job=~\"rds.*\"},\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\"))  * count by (agent_type) (label_replace(process_resident_memory_bytes{instance=~\"$node_name\",job=\"prometheus\"},\"agent_type\", \"rds_exporter\", \"\", \"\")))"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "stat",
   "description": "Shows the total number of virtual CPUs on the host. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}) or \n(1-absent(node_cpu_seconds_total{node_name=~\"$node_name\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{node_name=~\"$node_name\"} or up * 0)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Shows the total amount of RAM of the host. An Exporter is a software library that provides metrics to PMM.\n\nSee also:",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$node_name\"})"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (agent_type) (process_open_fds{node_name=~\"$node_name\"}) or sum by (agent_type) (label_replace(label_replace(process_open_fds{job=~\"rds.*\"},\"agent_type\", \"rds_exporter\", \"job\", \"rds_exporter_(.*)\"),\"node_name\",\"pmm-server\",\"\",\"\"))  * count by (agent_type) (label_replace(process_open_fds{instance=~\"$node_name\",job=\"prometheus\"},\"agent_type\", \"rds_exporter\", \"\", \"\")))"
    }
   ]
  }
 ]
}