{
 "title": "Databases Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "service_type",
    "label": "Engine",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   { "name": "qthres", "label": "Query Time", "query": "0.001,0.010,0.100,1,10" },
   {
    "name": "slowq",
    "label": "slowq",
    "query": "SELECT count(*)\n   FROM pmm.metrics\n   WHERE service_type = '${service_type}'\n     AND ( period_start  >= $__fromTime AND period_start <= $__toTime )\n    AND m_query_time_sum/m_query_time_cnt > ${qthres}"
   },
   {
    "name": "srvcnt",
    "query": "select count(*) from services where service_type = '${service_type}';"
   },
   {
    "name": "rangeCustom",
    "query": "select ($__toTime - $__fromTime)/60"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": " <div style=\"\n          color: #F9A100; \n          font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue,Helvetica,Arial,sans-serif; \n          letter-spacing: 0.011em; \n          font-weight: 600;\n          font-size: 16px;\n          -webkit-font-smoothing: antialiased;\n          border: 0px solid #ffffff;\n          border-radius: 10px;\n          background: #FFEFBA;  /* fallback for old browsers */\n          background: -webkit-linear-gradient(to right, #FFFFFF, #FFEFBA);  /* Chrome 10-25, Safari 5.1-6 */\n          background: linear-gradient(to right, #FFFFFF, #FFEFBA); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n          padding: 8px;\n          display:block;\n          width:100%;\n          height:83px;\n          \"> <span style=\"\n          color: #400004; \n          font-size: 25px;\n          \"> ${srvcnt} ${service_type} </span><br/><a href=\"/graph/inventory/services\" target=\"_blank\">Databases monitored</a></div>"
   }
  },
  {
   "title": "Execution time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT period_start, service_name, avg(m_query_time_sum/m_query_time_cnt) \"Execution_time\"\nFROM pmm.\"metrics\" WHERE   ( period_start  >= $__fromTime AND period_start <= $__toTime ) and service_type like '%$service_type%' GROUP BY period_start, service_name ORDER BY period_start ASC "
    }
   ]
  },
  {
   "title": "Executed Queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, avg by (service_name) (irate(mysql_global_status_questions{service_type=~\"$service_type\"})))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(5, avg by (service_name) (rate(pg_stat_database_xact_commit{service_type=~\"$service_type\"}[$interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "topk(5, avg by (service_name) (rate(mongodb_op_counters_total{service_type=~\"$service_type\",type!=\"command\"}[$interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "*Not real time. QAN is expected to have some minutes of lag",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": {
    "content": " <div style=\"\n          color: #FFFFFF; \n          font-family: -apple-system, BlinkMacSystemFont, Helvetica Neue,Helvetica,Arial,sans-serif; \n          letter-spacing: 0.011em; \n          font-weight: 600;\n          font-size: 15px;\n          -webkit-font-smoothing: antialiased;\n          border: 0px solid #ffffff;\n          border-radius: 10px;\n          background: #23074d;  /* fallback for old browsers */\n          background: -webkit-linear-gradient(to right, #cc5333, #23074d);  /* Chrome 10-25, Safari 5.1-6 */\n          background: linear-gradient(to right, #cc5333, #23074d); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */\n          padding: 8px;\n          display:block;\n          width:100%;\n          height:80px;\n          \"> <span style=\"\n          color: #FBEEC1; \n          font-size: 20px;\n          \"> ${slowq} </span>Queries slower than ${qthres} sec(s) in the last ${rangeCustom} minutes*\n          </br></div>"
   }
  },
  {
   "title": "Lowest Uptime (top 3)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "bottomk(3,range_last(mysql_global_status_uptime{service_type=\"$service_type\"}[30s]))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "bottomk(3,range_last(pg_postmaster_uptime_seconds{service_type=\"$service_type\"}[30s]))",
     "legendFormat": "{{service_name}}"
    },
    {
     "expr": "bottomk(3,range_last(mongodb_instance_uptime_seconds{service_type=\"$service_type\"}[30s]))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(period_start) as time, service_name \"Service\", username, fingerprint \"Query\", avg(m_query_time_sum/m_query_time_cnt) \"Execution_time\" FROM pmm.\"metrics\" WHERE ( period_start  >= $__fromTime AND period_start <= $__toTime ) AND ( service_type LIKE '%$service_type%' ) GROUP BY service_name, username, fingerprint , m_query_time_sum, time ORDER BY time DESC LIMIT 10000",
     "selectedFormat": 1
    }
   ]
  }
 ]
}