{
 "title": "PXC Galera Cluster Summary (experimental)",
 "tags": [
  "Percona",
  "MySQL_HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mysql_galera_variables_info, cluster)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "⚠️ Disclaimer ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "## 🛎️ Important\n\nThis Experimental Dashboard is not a part of the official Percona Monitoring and Management (PMM) deployment and might be updated. \nWe ship this Dashboard to obtain feedback from our users. \n\nOnce we officially release this Dashboard, it will be moved to the appropriate folder. \n\n## ✨ About Dashboard\n\nThis Dashboard is a new-experimental PXC Cluster Summary dashboard in PMM.\n\nBefore using this Dashboard, ensure to set the ‘cluster’ label when you add your PXC to PMM. For more details, please check this [doc.](https://per.co.na/pmm_admin)\n\nTo provide feedback on the Dashboard, please use [this topic](https://forums.percona.com/t/feedback-needed-experimental-pxc-cluster-summary-dashboard-for-pmm/16381?u=duygu.aksoy_demo) in our forum. 🙏"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (group by(cluster) (mysql_global_status_wsrep_cluster_size{cluster=~\"$cluster\", environment=~\"$environment\"}))"
    },
    {
     "expr": "count (avg by (cluster) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"}) == 4)"
    },
    {
     "expr": "count (avg by (cluster) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"}) == 3) or count (avg by (cluster) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"}) == 2) or count (avg by (cluster) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"}) == 1)"
    },
    {
     "expr": "count (avg by (cluster)(mysql_global_status_wsrep_cluster_status{cluster=~\"$cluster\", environment=~\"$environment\"})!=1)"
    }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (group by(service_name) (mysql_global_status_wsrep_cluster_size{cluster=~\"$cluster\", environment=~\"$environment\"}))"
    },
    {
     "expr": "sum (group by(service_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 4)) "
    },
    {
     "expr": "sum (group by(service_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 1))\n\n"
    },
    {
     "expr": "sum (group by(service_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 2)) "
    },
    {
     "expr": "sum (group by(service_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 3)) "
    }
   ]
  },
  {
   "title": "Node Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (group by(node_name) (mysql_global_status_wsrep_cluster_size{cluster=~\"$cluster\", environment=~\"$environment\"}))"
    },
    {
     "expr": "sum (group by(node_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 4)) "
    },
    {
     "expr": "sum (group by(node_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 1))\n\n"
    },
    {
     "expr": "sum (group by(node_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 2)) "
    },
    {
     "expr": "sum (group by(node_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"} == 3)) "
    }
   ]
  },
  {
   "title": "Active Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (grafana_alerting_alerts{state=\"alerting\"})"
    }
   ]
  },
  {
   "title": "Cluster Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (cluster) (group by (node_name,cluster) (mysql_global_status_wsrep_cluster_size{cluster=~\"$cluster\", environment=~\"$environment\"}))",
     "legendFormat": "{{cluster}} | Node Size"
    },
    {
     "expr": "avg by (cluster)(mysql_global_status_wsrep_cluster_status{cluster=~\"$cluster\", environment=~\"$environment\"})",
     "legendFormat": "{{cluster}} | Status"
    },
    {
     "expr": "avg by (cluster) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"})",
     "legendFormat": "{{cluster}} | State"
    },
    {
     "expr": "sum by (cluster) (group by (cluster,service_name) (mysql_galera_status_info{cluster=~\"$cluster\", environment=~\"$environment\"}))",
     "legendFormat": "{{cluster}} | Service Size"
    }
   ]
  },
  {
   "title": "Service Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (service_name) (group by (service_name) (mysql_global_status_wsrep_cluster_size{cluster=~\"$cluster\", environment=~\"$environment\"}))",
     "legendFormat": "{{service_name}} | Node Size"
    },
    {
     "expr": "avg by (service_name)(mysql_global_status_wsrep_cluster_status{cluster=~\"$cluster\", environment=~\"$environment\"})",
     "legendFormat": "{{service_name}} | Status"
    },
    {
     "expr": "avg by (service_name) (mysql_global_status_wsrep_local_state{cluster=~\"$cluster\", environment=~\"$environment\"})",
     "legendFormat": "{{service_name}} | State"
    }
   ]
  },
  {
   "title": "Cluster and Service Size History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum (group by (cluster) (mysql_galera_status_info {cluster=~\"$cluster\", environment=~\"$environment\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum (group by(service_name) (mysql_global_status_wsrep_cluster_size{cluster=~\"$cluster\", environment=~\"$environment\"}))",
     "legendFormat": "Services"
    }
   ]
  },
  {
   "title": "Query / second (QPS) ",
   "type": "timeseries",
   "description": "**Query / second (QPS)**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum (avg by (cluster) (rate(mysql_global_status_queries{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_queries{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))\n",
     "legendFormat": "Summary QPS"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Used Connections",
   "type": "timeseries",
   "description": "Max Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (max_over_time(mysql_global_status_max_used_connections{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nmax_over_time(mysql_global_status_max_used_connections{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Max Used Connections - {{cluster}}"
    }
   ]
  },
  {
   "title": "Aborted Connections",
   "type": "timeseries",
   "description": "**Aborted Connections**\n\nWhen a given host connects to MySQL and the connection is interrupted in the middle (for example due to bad credentials), MySQL keeps that info in a system table (since 5.6 this table is exposed in performance_schema).\n\nIf the amount of failed requests without a successful connection reaches the value of max_connect_errors, mysqld assumes that something is wrong and blocks the host from further connection.\n\nTo allow connections from that host again, you need to issue the ``FLUSH HOSTS`` statement.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_aborted_connects{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_aborted_connects{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Aborted Connects (attempts) - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_aborted_clients{service_name=~\"$service_name\"}[$interval]) or \nirate(mysql_global_status_aborted_clients{service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Aborted Clients (timeout) - {{cluster}}"
    }
   ]
  },
  { "title": "Query Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Receive Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (mysql_global_status_wsrep_local_recv_queue{cluster=~\"$cluster\", environment=~\"$environment\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Send Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (mysql_global_status_wsrep_local_send_queue{cluster=~\"$cluster\", environment=~\"$environment\"})",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Flow Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Flow Control",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_wsrep_flow_control_sent{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Sent - {{cluster}}"
    },
    {
     "expr": "avg by (cluster) (rate(mysql_global_status_wsrep_flow_control_recv{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_recv{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Received  - {{cluster}}"
    },
    {
     "expr": "clamp_max(avg by (cluster) ((rate(mysql_global_status_wsrep_flow_control_paused_ns{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))/1000000000,1)",
     "legendFormat": "Paused  - {{cluster}}"
    }
   ]
  },
  {
   "title": "Flow Control Paused Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "clamp_max(avg by (cluster) ((rate(mysql_global_status_wsrep_flow_control_paused_ns{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_paused_ns{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))/1000000000,1)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Flow Control Messages Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(avg by (cluster) (rate(mysql_global_status_wsrep_flow_control_sent{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_flow_control_sent{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Writeset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Writeset Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) ((rate(mysql_global_status_wsrep_received_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_received_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Writeset Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) ((rate(mysql_global_status_wsrep_replicated_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval])or irate(mysql_global_status_wsrep_replicated_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Total Bytes In/Out - Backend and Frontend",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (cluster) (rate(haproxy_frontend_bytes_in_total{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(haproxy_frontend_bytes_in_total{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Frontend IN - {{cluster}}"
    },
    {
     "expr": "avg by (cluster) (rate(haproxy_frontend_bytes_out_total{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(haproxy_frontend_bytes_out_total{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Frontend OUT - {{cluster}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Galera Replication Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (cluster) (avg_over_time(mysql_galera_evs_repl_latency_avg_seconds{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]))",
     "legendFormat": "Average - {{cluster}}"
    },
    {
     "expr": "avg by (cluster) (max_over_time(mysql_galera_evs_repl_latency_max_seconds{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]))",
     "legendFormat": "Maximum - {{cluster}}"
    },
    {
     "expr": "avg by (cluster) (min_over_time(mysql_galera_evs_repl_latency_min_seconds{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]))",
     "legendFormat": "Minimum - {{cluster}}"
    }
   ]
  },
  {
   "title": "Average Galera Replication Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (cluster) (avg_over_time(mysql_galera_evs_repl_latency_avg_seconds{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]))",
     "legendFormat": "Latency Average - {{cluster}}"
    }
   ]
  },
  {
   "title": "Maximum Galera Replication Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (cluster) (max_over_time(mysql_galera_evs_repl_latency_max_seconds{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]))",
     "legendFormat": "Latency Maximum - {{cluster}}"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Transactions Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) ((rate(mysql_global_status_wsrep_received{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_received{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Transactions Replicated",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) ((rate(mysql_global_status_wsrep_replicated{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_wsrep_replicated{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Average Incoming Transaction Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) ((rate(mysql_global_status_wsrep_received_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) / (rate(mysql_global_status_wsrep_received{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) > 0) or irate(mysql_global_status_wsrep_received_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]) / (irate(mysql_global_status_wsrep_received{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]) > 0)))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Average Replicated Transaction Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) ((rate(mysql_global_status_wsrep_replicated_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) / (rate(mysql_global_status_wsrep_replicated{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) > 0) or irate(mysql_global_status_wsrep_replicated_bytes{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]) / (irate(mysql_global_status_wsrep_replicated{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]) > 0)))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "CPU Busy $cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 126 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by () (\n(sum by (node_name,cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or  (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!='idle',mode!=\"iowait\"}[5m]),1)) ))*100 or sum by () (avg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"total\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\",mode!=\"idle\",mode!=\"total\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Memory Busy $cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 126 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by () (clamp_max(avg by (node_name) (container_memory_usage_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"} * 100 / container_spec_memory_limit_bytes{node_name=~\"$node_name\",id=~\"/kubepods.*\",container!~\"POD|pmm-client|backup-agent|\"}),100) or avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$node_name\"} or (node_memory_MemFree_bytes{node_name=~\"$node_name\"} + node_memory_Buffers_bytes{node_name=~\"$node_name\"} + node_memory_Cached_bytes{node_name=~\"$node_name\"})) / node_memory_MemTotal_bytes{node_name=~\"$node_name\"} * 100))"
    }
   ]
  },
  {
   "title": "Storage $cluster",
   "type": "stat",
   "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 126 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$node_name\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype)))"
    }
   ]
  },
  {
   "title": "Network IO $cluster",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 126 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(node_network_receive_bytes_total{node_name=~\"$node_name\",device!=\"lo\"}[$interval]) \nor irate(node_network_receive_bytes_total{node_name=~\"$node_name\",device!=\"lo\"}[5m]) \nor max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[$interval]) \nor max_over_time(rdsosmetrics_network_rx{node_name=~\"$node_name\"}[5m]))\n+\nsum(rate(node_network_transmit_bytes_total{node_name=~\"$node_name\",device!=\"lo\"}[$interval]) \nor irate(node_network_transmit_bytes_total{node_name=~\"$node_name\",device!=\"lo\"}[5m])\nor max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[$interval]) \nor max_over_time(rdsosmetrics_network_tx{node_name=~\"$node_name\"}[5m]))"
    }
   ]
  },
  { "title": "MySQL Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 } },
  {
   "title": "Client Thread Activity",
   "type": "timeseries",
   "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (max_over_time(mysql_global_status_threads_connected{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Peak Threads Connected - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (max_over_time(mysql_global_status_threads_running{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Peak Threads Running - {{cluster}}"
    },
    {
     "expr": "avg by (cluster,environment) (avg_over_time(mysql_global_status_threads_running{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Avg Threads Running - {{cluster}}"
    }
   ]
  },
  {
   "title": "Thread Cache",
   "type": "timeseries",
   "description": "**MySQL Thread Cache**\n\nThe thread_cache_size variable sets how many threads the server should cache to reuse. When a client disconnects, the client's threads are put in the cache if the cache is not full. It is autosized in MySQL 5.6.8 and above (capped to 100). Requests for threads are satisfied by reusing threads taken from the cache if possible, and only when the cache is empty is a new thread created.\n\n* *Threads_created*: The number of threads created to handle connections.\n* *Threads_cached*: The number of threads in the thread cache.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (max_over_time(mysql_global_variables_thread_cache_size{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or\nmax_over_time(mysql_global_variables_thread_cache_size{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Thread Cache Size - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (max_over_time(mysql_global_status_threads_cached{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_cached{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Threads Cached - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_threads_created{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_threads_created{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Threads Created - {{cluster}}"
    }
   ]
  },
  {
   "title": "Temporary Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_created_tmp_tables{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_created_tmp_tables{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Created Tmp Tables - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_created_tmp_disk_tables{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_created_tmp_disk_tables{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Created Tmp Disk Tables - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_created_tmp_files{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_created_tmp_files{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Created Tmp Files - {{cluster}}"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "timeseries",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_select_full_join{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_select_full_join{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Select Full Join - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_select_full_range_join{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_select_full_range_join{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Select Full Range Join - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_select_range{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_select_range{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Select Range - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_select_range_check{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_select_range_check{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Select Range Check - {{cluster}}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_select_scan{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or \nirate(mysql_global_status_select_scan{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Select Scan - {{cluster}}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "timeseries",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster,handler) (rate(mysql_global_status_handlers_total{cluster=~\"$cluster\", environment=~\"$environment\", handler!~\"commit|rollback|savepoint.*|prepare\"}[$interval]) or \nirate(mysql_global_status_handlers_total{cluster=~\"$cluster\", environment=~\"$environment\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m]))",
     "legendFormat": "{{ handler }} - {{cluster}}"
    }
   ]
  },
  {
   "title": "InnoDB Data Reads",
   "type": "timeseries",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_innodb_data_reads{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Data Reads - {{cluster}}"
    },
    {
     "expr": "avg by (cluster) ((rate(mysql_global_status_innodb_data_reads{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_innodb_data_reads{service_name=~\"$service_name\"}[5m]))+ (rate(mysql_global_status_innodb_data_writes{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{cluster=~\"$cluster\", environment=~\"$environment\"}[5m])))",
     "legendFormat": "Data Total IOPS - {{cluster}}"
    }
   ]
  },
  {
   "title": "InnoDB Data Writes",
   "type": "timeseries",
   "description": "**InnoDB I/O**\n\n_Data Writes_ - The total number of InnoDB data writes.\\\n_Data Reads_ - The total number of InnoDB data reads (OS file reads).\\\n_Log Writes_ - The number of physical writes to the InnoDB redo log file.\\\n_Data Fsyncs_ - The number of fsync() operations. The frequency of fsync() calls is influenced by the setting of the `innodb_flush_method` configuration option.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_innodb_data_writes{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_innodb_data_writes{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Data Writes - {{cluster}}"
    }
   ]
  },
  {
   "title": "InnoDB FSyncs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (cluster) (rate(mysql_global_status_innodb_data_fsyncs{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_innodb_data_fsyncs{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Data Fsyncs - {{cluster}}"
    },
    {
     "expr": "avg by (cluster) (rate(mysql_global_status_innodb_os_log_fsyncs{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_global_status_innodb_os_log_fsyncs{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "Log Fsyncs - {{cluster}}"
    }
   ]
  },
  {
   "title": "InnoDB Locking",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (cluster) (rate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total{cluster=~\"$cluster\", environment=~\"$environment\"}[$interval]) or irate(mysql_info_schema_innodb_metrics_lock_lock_rec_lock_requests_total{cluster=~\"$cluster\", environment=~\"$environment\"}[5m]))",
     "legendFormat": "InnoDB Row Lock Current Waits - {{cluster}}"
    }
   ]
  }
 ]
}